blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Community Discussions
    url: https://github.com/MiserableGamer/ONI-Miserable-Mods/discussions
    about: Have a general question or want to discuss the mods? Use Discussions instead!

